### ISSUE TITLE
Could you tell me which 5G testbed you used for the 5G sniffer testing?

### ISSUE THREAD

**Issue by gw-space** [spritelab/5GSniffer#5]
I'm looking to experiment with 5gsniffer, and I want to set up a 5G testbed. Could you tell me what tools you used to create testbeds for both the 5G access network and the core network? I want to replicate a similar environment for testing.

**Comment by NorbLd** [comment]
Sorry for the late response. I have used srsRAN 5G project for the RAN, and open5GS for the core network. You can find instructions in the srsRAN project: https://docs.srsran.com/projects/project/en/latest/tutorials/source/cotsUE/source/index.html

**Comment by gw-space** [comment]
Thank you for your response. 
Following the link you provided, I have successfully set up a testbed and installed 5gsniffer to capture the MIB live (FDD). However, even though I calculated the subcarrier offset and added it to the sniffer configuration file as instructed on the readme page, and I believe I have entered the correct values for other parameters using information from the MIB and SIB, PDCCH decoding is not being performed. In my settings, the calculated subcarrier offset comes out as a negative value. Could the negative subcarrier offset be the issue?

**Comment by gw-space** [comment]
I've successfully obtained the MIB and achieved PDCCH decoding by setting the subcarrier_offset value to be positive. However, I have additional questions:

When the subcarrier spacing is set to 30kHz, I'm unable to obtain the MIB.
After setting the frequency to above 2.5GHz and initiating the sniffer operation, it defaults back to 627.75MHz (default value), preventing sniffing in the frequency band above 2.5GHz.
Does the current code not support these two scenarios?
Thank you for your always kind responses.

**Comment by NorbLd** [comment]
Hello,

I believe a negative offset should not be a problem, but I have not encountered a negative value before. It seems that the current default configuration for PDCCH/CORESET in srsRAN has changed since I last tried. I will run my testbed on the latest srsRAN version and I will let you know if I encounter any issues making the 5GSniffer work. Please let me know if you have any additional questions.

**Comment by jing07140680** [comment]
Hi, I met the same problem that the sniffer cannot decode PDCCH after capturing the MIBs. In my case,I used srsRAN_Project(23.10 for gNB), srsRAN_4G(23.11 for UE), and Open5GS the subcarrier offet is not negtive, the setting I used is band 3, 102 PRBs, I forced the center freqency aligned with the  bandwith center frequency in the first place, I printed out eccential information to calcuated the offset. I have the following two observations and don't know if they are normal.... (1) the sniffer only capture the MIB serval times (2) it shows high correlation but in the wrong slot, AL and CCE. (not sure if this would be helpful to dignose the problem). BTW, may I ask which srsRAN_Project release you previously used?

**Comment by Matheus-Garbelini** [comment]
@NorbLd Can you mention what commit of srsRan you have used for the gNB? And possibly the gNB config. file you have used. Currently, we cannot decode further after decoding MIB.

**Comment by NorbLd** [comment]
Hello all,

I have just created a clean install of the latest version of srsRAN_Project as of today, and I connected a Pixel 5 phone to the 5G gNB. While performing traffic on the phone, I ran the 5GSniffer, and I am able to decode DCIs with almost no changes to the config file. I have used the following config for srsRAN:

```
rf_driver:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
...

cell_cfg:
  dl_arfcn: 125500                                              # ARFCN of the downlink carrier (center frequency).
  band: 71                                                      # The NR band.
  channel_bandwidth_MHz: 10                                     # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                                                # Subcarrier spacing in kHz used for data.
...

```  
  
As for the sniffer config, I have used the same config as I used in the past (SpriteLab-Private5G.toml), and I only modified the center frequency, matching the dl_ssb_arfcn=125530 config of the 5G gNB:

`frequency = 627750000 -> frequency = 627650000
`
If you want to decode from a file, please run `uhd_rx_cfile -r 23040000 -f 627650000 /tmp/file.fc32`. Additionally, it is a good idea to visually inspect the spectrum to make sure there is traffic.

Please let me know if this works. It could be that other bands have some peculiarities we did not account for initially, I will try to see what is the problem with other srsRAN configs/bands.

Moreover, when I implemented the 5GSniffer, the operators in my area were only using low band FDD frequencies. For TDD bands, currently we can only get MIB due to required changes to adapt to the frame structure of TDD. Hopefully we can get this working as well.

Thank you,
